version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch
        environment:
        PG_HOST: 127.0.0.1
        PG_USER: root
        NODE_ENV: production
        S3Bucket: "s3://dev-react-static-test-s3bucket-ujwcuvt88ksu/"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install and build
          command: |
            npm install
            npm run-script build
      - store_artifacts:
          path: ~/repo/build
          destination: ~/repo/artifacts
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Deploy to s3
          command: |
            apk add --update python py-pip
            pip install awsebcli --user
            echo $(S3Bucket)
            aws s3 cp ~/repo/artifacts/build s3://dev-react-static-test-s3bucket-ujwcuvt88ksu/ --recursive
