version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.9.4-stretch
              environment:
                PG_HOST: 127.0.0.1
                PG_USER: root
                NODE_ENV: test
        steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-
            - run:
                name: project dependencies
                command: |
                    npm install
                    sudo npm install sequelize-cli -g
            - save_cache:
                    key: v1-dependencies-{{ checksum "package.json" }}
                    paths:
                        - node_modules
    test:
        docker:
            - image: circleci/node:8.9.4-stretch
              environment:
                PG_HOST: 127.0.0.1
                PG_USER: root
                NODE_ENV: test
        steps:
            - run:
                name: test
                command: npm test
           
            - run:
                name: database setup
                command: |
                    npm run migrate
                    npm run seeds
                    npm run excel
            
    deploy:
        docker:
            - image: circleci/node:8.9.4-stretch
              environment:
                PG_HOST: 127.0.0.1
                PG_USER: root
                NODE_ENV: test
        steps:
            - run:
                name: Install dependencies
                working_directory: /
                command: |
                    sudo apt-get install python-pip python-dev build-essential
                    sudo pip install awsebcli --upgrade
            - run:
                name: Deploy to AWS 
                command: |
                    echo Deploying
workflows:
    build_and_test:
    jobs:
      - build
      - test


