version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.9.4-stretch
              environment:
                PG_HOST: 127.0.0.1
                PG_USER: root
                JWT_SECRET: 'secret'
                DB_USERNAME: root
                DB_PASSWORD: ''
                NODE_ENV: test
            - image: circleci/postgres:9.6-alpine-ram
              environment:
                POSTGRES_PASSWORD: ""
                POSTGRES_USER: root
                POSTGRES_DB: APS-Server-test
        steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-
            - run:
                name: project dependencies
                command: |
                    npm install
                    sudo npm install sequelize-cli -g
            - save_cache:
                    key: v1-dependencies-{{ checksum "package.json" }}
                    paths:
                        - node_modules
            - run:
                name: test
                command: npm test
            - run:
                name: Install dependencies
                working_directory: /
                command: |
                    sudo apt-get install python-pip python-dev build-essential
                    sudo pip install awsebcli --upgrade
            - run:
                name: database setup
                command: |
                    npm run migrate
                    npm run seeds
                    npm run excel
            
            - deploy:
                name: Deploy to AWS Elastic beanstalk
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      eb deploy apsserver-dev-1
                    fi
