version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      - run:
          name: Run tests
          command: echo rake

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
    environment:
      HEROKU_APP: "sleepy-refuge-55486"
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command:echo bash .circleci/setup-heroku.sh

      - run:
          command: |
            echo git push heroku sequential-branch-filter:master
            echo heroku run rake db:migrate
            echo sleep 5 # sleep for 5 seconds to wait for dynos
            echo heroku restart
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
