version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch
        environment:
        PG_HOST: 127.0.0.1
        PG_USER: root
        NODE_ENV: production
        S3Bucket: "s3://dev-react-static-test-s3bucket-ujwcuvt88ksu/"
    working_directory: ~/repo
    steps:
      - run:
          name: install and build
          command: |
            echo $NODE_ENV
            echo  $S3Bucket
