version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch
        environment:
        PG_HOST: 127.0.0.1
        PG_USER: root
        NODE_ENV: production
        S3Bucket: "s3://dev-react-static-test-s3bucket-ujwcuvt88ksu/"
        SHORT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
    working_directory: ~/repo
    steps:
      - run:
          name: install and build
          command: |
            echo "${CIRCLE_BRANCH}" &&
            echo "${PG_HOST}" &&
            echo "$AWS_ACCESS_KEY_ID" 