version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch
        environment:
        PG_HOST: 127.0.0.1
        PG_USER: root
        NODE_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      # Bundle install dependencies
      - run: echo bundle install --path vendor/bundle
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: project dependencies
          command: |
            npm install
            npm build
      - store_artifacts:
          path: ~/repo/artifacts
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run test
          
  dependencies:
    pre:
      - pip install awsebcli --user
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    environment:
      HEROKU_APP: "sleepy-refuge-55486"
    awsdev:
      steps:
        branch: master
        commands:
          - aws s3 cp ~/repo/build s3://dev-react-static-test-s3bucket-ujwcuvt88ksu/ --recursive
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test
      - hold:
          type: approval
          requires:
           - build
           - test
      - deploy:
          requires:
            - hold